feat: inquiry, review Action_tracking 추가
likelion-kookmin/daedong-food-map pull request #107
Opened 2021-08-04 14:26 UTC by sh981013s

inquiry, review count 와 로그 추가:

![image](https://user-images.githubusercontent.com/81363031/128198570-d22be726-700c-408b-8d85-0f523c21234c.png)

2021-08-04 14:36 UTC, shinkeonkim requested changes

2021-08-04 14:36 UTC, shinkeonkim commented on backend/action_trackings/signals.py
> +    user.review_count += 1
해당 유저가 리뷰를 취소했을 때,(destory API가 호출되었을 때) review_count를 -1 해주는 코드도 있으면 좋을 같아요

2021-08-04 14:36 UTC, shinkeonkim commented on backend/action_trackings/signals.py
> +
요것도 마찬가지로 pre-commit이 안잡았나요 🤔

2021-08-04 14:36 UTC, shinkeonkim commented on backend/action_trackings/signals.py
> +    user.inquiry_count += 1
해당 유저가 신고를 취소했을 때, inquiry_count를 -1해주는 코드가 있으면 좋을 것 같아요. action tracking 상에서는 추적해도 그만, 안해도 그만인 것 같습니다.

2021-08-04 15:28 UTC, sh981013s commented
![image](https://user-images.githubusercontent.com/81363031/128208948-7b16388b-a69f-4999-8c29-61661024bf73.png)

로그 남는 것과 count value -1  되는 것 확인했어요!

2021-08-04 16:22 UTC, sh981013s commented
view 에 있는 함수들로 옮겼습니다!

2021-08-05 11:51 UTC, shinkeonkim commented
> view 에 있는 함수들로 옮겼습니다!

수정하신 내용을 push를 안하신 것 같아요.

2021-08-05 12:23 UTC, sh981013s commented
아 확인하고 푸쉬했습니다!

2021-08-05 13:57 UTC, shinkeonkim approved these changes
남겨놓은 코멘트는 추가 작업으로 진행해주시고, 요건 머지해주세욥 ㅎㅎ

2021-08-05 13:57 UTC, shinkeonkim commented on backend/action_trackings/models.py
> +    DELETE_INQUIRY = '신고 삭제', _('destroy_inquiry')
변수명도 DESTROY와 DELETE를 맞춰주시면 좋을 것 같습니다.
헌데, 아직 관련해서 tracking이 안 만들어지고 있으니 만드는 작업과 함께해서 이후에 진행해주세요.
views.py 상에서 ActionTracking.objects.create() 를 이용하거나 혹은
ActionTracking 모델 클래스 상에 메서드를 따로 만드셔서 구현하셔도 될 것 같습니다.

2021-08-05 14:04 UTC, merged