feat: reports #index api 연결
likelion-kookmin/daedong-food-map pull request #99
Opened 2021-08-04 10:10 UTC by shinkeonkim

2021-08-05 02:19 UTC, kkIIun approved these changes
LGMT!

2021-08-05 05:08 UTC, minjj0905 approved these changes

2021-08-05 05:20 UTC, minjj0905 commented on frontend/src/sagas/index.js
>  import { apiUrl } from '../config/api.config';
import문 절대경로로 작성해주세용 🙏

2021-08-05 05:21 UTC, minjj0905 requested changes
import문 절대경로로 수정ㅈ

2021-08-05 05:21 UTC, minjj0905 commented on frontend/src/sagas/index.js
>  import { apiUrl } from '../config/api.config';
import 절대경로로 작성해주세용 (src 아래는 그냥 폴더명으로 시작해두 댑니다)
-> import { apiUrl } from 'config/api.config';

2021-08-05 11:52 UTC, shinkeonkim commented on frontend/src/sagas/index.js
>  import { apiUrl } from '../config/api.config';
이건 굳이.. 바꿔야해요?

2021-08-05 11:52 UTC, shinkeonkim commented on frontend/src/sagas/index.js
>  import { apiUrl } from '../config/api.config';
어차피 이건 모두 sagas 폴더 내부 안에서 관리되는건데, 오히려 절대경로가 더 가독성을 해친다고 생각해요

2021-08-06 00:12 UTC, minjj0905 commented on frontend/src/sagas/index.js
>  import { apiUrl } from '../config/api.config';
앗 ,,, 그런가 ..?

2021-08-06 00:12 UTC, minjj0905 approved these changes

2021-08-06 12:06 UTC, merged